docs: update links (#63)
EthicalSource/hippocratic-license-3 pull request #64
Opened 2022-12-24 01:39 UTC by olets

# Milestone

Keeps repo links up to date.

# Getting there

- For #63 Changes links that point to the archived repo https://github.com/EthicalSource/hippocratic-license to point to this one.
- Fixes the link to a markdown section the heading of which has changed.

# Interesting bits

x

# What I need help with

x

# What's next

x

2022-12-30 11:18 UTC, nilsnh requested changes
Thank you for this fix @olets! I only had a minor nitpick on the suggested changes. :)

2022-12-30 11:18 UTC, nilsnh commented on README.md
> +* Fork [the repository](https://github.com/EthicalSource/hippocratic-license-3-3/blob/release/CONTRIBUTING.md)
Small typo here I think?

2022-12-30 15:48 UTC, olets commented on README.md
> +* Fork [the repository](https://github.com/EthicalSource/hippocratic-license-3-3/blob/release/CONTRIBUTING.md)
Good catch! Fixed

2022-12-30 16:08 UTC, merged

2022-12-30 16:09 UTC, nilsnh reviewed
Great work! Merged :raised_hands:

2023-12-29 11:21 UTC, amalbenny commented
Why do you keep this issue, even after solved.